export const CALCULATOR_CREATE_REQUEST = 'CALCULATOR_CREATE_REQUEST'
export const CALCULATOR_CREATE_SUCCESS = 'CALCULATOR_CREATE_SUCCESS'
export const CALCULATOR_CREATE_FAIL = 'CALCULATOR_CREATE_FAIL'

export const CALCULATOR_MINE_LIST_REQUEST = 'CALCULATOR_MINE_LIST_REQUEST'
export const CALCULATOR_MINE_LIST_SUCCESS = 'CALCULATOR_MINE_LIST_SUCCESS'
export const CALCULATOR_MINE_LIST_FAIL = 'CALCULATOR_MINE_LIST_FAIL'
