export const CALCULATOR_CREATE_REQUEST = 'CALCULATOR_CREATE_REQUEST'
export const CALCULATOR_CREATE_SUCCESS = 'CALCULATOR_CREATE_SUCCESS'
export const CALCULATOR_CREATE_FAIL = 'CALCULATOR_CREATE_FAIL'