export const MEAL_LIST_REQUEST = 'MEAL_LIST_REQUEST'
export const MEAL_LIST_SUCCESS = 'MEAL_LIST_SUCCESS'
export const MEAL_LIST_FAIL = 'MEAL_LIST_FAIL'

export const MEAL_REMOVE_REQUEST = 'MEAL_REMOVE_REQUEST'
export const MEAL_REMOVE_SUCCESS = 'MEAL_REMOVE_SUCCESS'
export const MEAL_REMOVE_FAIL = 'MEAL_REMOVE_FAIL'

export const MEAL_ONE_REQUEST = 'MEAL_ONE_REQUEST'
export const MEAL_ONE_SUCCESS = 'MEAL_ONE_SUCCESS'
export const MEAL_ONE_FAIL = 'MEAL_ONE_FAIL'