export const GET_ALL_PROGRAM_REQUEST = 'GET_ALL_PROGRAM_REQUEST';
export const GET_ALL_PROGRAM_SUCCESS = 'GET_ALL_PROGRAM_SUCCESS';
export const GET_ALL_PROGRAM_FAIL = 'GET_ALL_PROGRAM_FAIL';

export const GET_ONE_PROGRAM_REQUEST = 'GET_ONE_PROGRAM_REQUEST';
export const GET_ONE_PROGRAM_SUCCESS = 'GET_ONE_PROGRAM_SUCCESS';
export const GET_ONE_PROGRAM_FAIL = 'GET_ONE_PROGRAM_FAIL';